### ISSUE TITLE
some suggestions for the new version

### ISSUE THREAD

**Issue by Pathsis** [geph-official/geph5#2]
Hello! I don't have the ability to comment on technical issues. From the perspective of an ordinary user, I have some suggestions for the new version:

1. Improve the icons for various system versions. For example, on macOS, the icon are too large and don't coordinate well with the default icons of the latest system.
2. Improve the experience of separating the client and GUI.Compared to version 3.x, the UX of 4.x couldn't be worse.
3. Improve the packaging and distribution of the Linux version.

Best wishes!

**Comment by nullchinchilla** [comment]
The GUI for Geph5 will be completely rewritten and much better, probably using something like https://www.egui.rs/ rather than the current web-stack way.
