### ISSUE TITLE
LINUX下VPN模式的DNS问题导致无法正常使用

### ISSUE THREAD

**Issue by Geography6877** [geph-official/geph5#21]
操作系统：ArchLinux
内核版本：6.10.2
GEPH5-GUI版本：2024.08.01最新代码编译
问题情况：使用sudo geph5-client-gui执行后，使用VPN模式，可以正常连接，SOCKS5可以正常使用。但不使用代理时无法解析网站，使用curl ip.sb时提示curl: (6) Could not resolve host: ip.sb

**Comment by Geography6877** [comment]
已经解决，但/etc/resolv.conf设置dns为127.0.0.1时（使用了dnscrypt-proxy）还是会Could not resolve host

**Comment by AnyWAT** [comment]
> GEPH5-GUI版本：2024.08.01最新代码

WIN版最新：2024.08.19
WIN版自动生成的 config.yaml 中的参数 spoof_dns 随着版本的更新，从 false 到了 true
图形模式下即使手动修改成F，正常运行后也会被自动改回T，只是命令行模式下不被程序修改。
敝人码盲，也运行有 dnscrypt-proxy 的WIN版貌似没问题。
