### ISSUE TITLE
ForceDirect选项未如预期生效

### ISSUE THREAD

**Issue by Geography6877** [geph-official/geph5#22]
操作系统：ArchLinux
内核版本：6.10.2
GEPH5-GUI版本：2024.08.01最新代码编译
问题情况：使用ForceDirect选项后依然获取桥，请核查？

**Comment by AnyWAT** [comment]
运行有 dnscrypt-proxy 的WIN10 系统，网桥模式如选“自动”，偶尔“出口位置”与“连接经由”为同一地址——被直接了？
