### ISSUE TITLE
support user info encryption

### ISSUE THREAD

**Issue by sussce** [geph-official/geph5#25]
support user info encryption, by replacing plain text (username,password) with encrypted keys

support user option *register*/*delete* in command-line client, by option *register* does the following: registering, encrypting, returning to the terminal or, saving to file for copy-and-paste in setting.yaml:
_username: keys
password: keys_

support *default_setting.yaml* in repo

**Comment by nullchinchilla** [comment]
It's actually on the roadmap to use key-based authentication with a UX similar to Mullvad's "account numbers", so the whole username/password infra is really a legacy thing.
