### ISSUE TITLE
增加关闭之后后台运行的功能

### ISSUE THREAD

**Issue by Pathsis** [geph-official/geph5#28]
现在必须最小化，任务栏得始终保留图标，对于一个后台运行的程序来说，实在不便。请求支持。

**Comment by AnyWAT** [comment]
>想开机即连，批处理：先启动命令行模式，立马运行图形模式，查看日志观察网速两不误——WIN10正常。（把批处理的快捷方式扔进开机启动程序组）
系统任务管理器——详细信息：
结束 geph5-client-gui.exe 进程，命令行模式继续；
结束内存较大的 conhost.exe 进程，图形模式继续。

**Comment by Pathsis** [comment]
@AnyWAT 多谢指教！但还是希望作者提供简单的“点击关闭按钮继续后台运行服务”的功能。

**Comment by AnyWAT** [comment]
以前有过，那样系统托盘仍然有程序图标。

**Comment by Pathsis** [comment]
@AnyWAT 保留系统托盘我可以接受，毕竟这也是常规操作。

**Comment by AnyWAT** [comment]
如果开始就说：改变用户界面右上角的操作“x”不是结束程序，而是最小化到系统托盘。也就木有如下的歧义了：
> 都没有不正是你的需求？

**Comment by nullchinchilla** [comment]
整个目前的gui是一个实验性的东西，都不一定最后会用egui这种方式
