### ISSUE TITLE
Geph5 client fails to connect under Fedora (KDE Plasma X11)

### ISSUE THREAD

**Issue by vikingsail** [geph-official/geph5#29]
[logsdb.txt](https://github.com/user-attachments/files/17302621/logsdb.txt)
Fedora (KDE spin on X11 session) 下迷霧通使用Geph4和Geph5版本都會導致client崩潰。但用另一台PC跑Ubuntu測試可用。
請問如何解決呢？

另外，Windows版本的客戶端有不用WebView 2.0可以使用的版本嗎？

**Comment by AnyWAT** [comment]
> logsdb.txt

里面有账户、密码明文，付费用户就借用了，谢谢。

> Windows版本的客戶端有不用WebView 2.0可以使用的版本嗎？

Geph5版本不就是。

**Comment by Geography6877** [comment]
试一下在Fedora 下直接编译geph5-client-gui看看。

**Comment by nullchinchilla** [comment]
这个应该解决了，可以再试试吗？

**Comment by AnyWAT** [comment]
贴主心已冷、人已冰冻，不再言语。
