### ISSUE TITLE
http代理入口会漏泄本地IPV6地址

### ISSUE THREAD

**Issue by Geography6877** [geph-official/geph5#35]
Firefox使用http代理入口会漏泄本地IPV6地址，使用socks5没有此问题。
测试地址:https://browserleaks.com/ip
![image](https://github.com/user-attachments/assets/8e5af72b-592d-49b5-98a9-06858a8b9fb7)

**Comment by AnyWAT** [comment]
在WIN系统，貌似2024/11/4 16:34版问题，现已更新2024/11/6 3:41，未测。

**Comment by nullchinchilla** [comment]
这个解决了： https://github.com/geph-official/geph5/commit/f2f35d87f3eda3819dde6877143612c9e43f145e

**Comment by AnyWAT** [comment]
WIN版V5再更新：2024/11/6 20:46 已修复
>使用http代理入口会漏泄本地IPV6地址

但图形VPN模式下的 geph5-client.exe 罢工，用下载的替换安装生成的 geph5-client.exe 后VPN可以连接了，并不是真正的VPN：浏览器代理扩展“直接连接”无法连网。
