### ISSUE TITLE
Client stops proxying traffic properly after the exit restarts

### ISSUE THREAD

**Issue by nullchinchilla** [geph-official/geph5#48]
The client appears to do a correct reconnect, but afterwards does not pass more traffic.

I am suspecting some sort of deadlock in the dispatching of to-be-proxied streams to workers.

**Comment by AnyWAT** [comment]
如若现有网页下迷雾通网速几乎一直趋零，打开其它链接的网页貌似能唤起使之正常。

**Comment by nullchinchilla** [comment]
This is now fixed. There is a combination of two bad behaviors that cause this:
- The concurrent sessions of Geph are run in futures that are `join`ed together, within the same task. This causes extremely unfair scheduling, which we attempt to fix by using a `smol::lock::Mutex`, but that causes lagginess when one thread gets stuck for a while while holding the lock.
- `picomux` has a bug where if a `PicoMux`'s driver thread dies, the `Stream`s associated do not all die. This is now fixed by moving all tasks inside the `PicoMux` into a `TaskReaper` to cancel them all together.
